import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LenisProvider from "@/Comonents/LenisProvider";
import Navbar from '@/Comonents/Navbar'
import Footer from "@/Comonents/Footer";
import PageTransition from "@/Comonents/PageTransition";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased min-h-screen bg-[url('/bg.jpg')] bg-cover bg-center bg-fixed`}
    >
      <body className="min-h-full flex flex-col lg:mx-14 md:mx-14 bg-white sm:mx-0">
       
      <LenisProvider>
        <PageTransition>
        <Navbar />

        {children}

        <Footer/>
        <div
  id="page-transition"
  className="fixed left-1/2 top-1/2 z-[9999] h-20 w-20 -translate-x-1/2 -translate-y-1/2 rounded-full bg-black pointer-events-none"
  style={{
    transform: "translate(-50%, -50%) scale(0)",
  }}
/>
</PageTransition>
        </LenisProvider>
        
      
      </body>
    </html>
  );
}
